### Python Numpy

###### Numerical Python

#### 1. Import Numpy

In [4]:
import numpy as np

#### 2. Creating Numpy Arrays

What are arrays?

Arrays as super lists

In [28]:
my_list = [i for i in range (5)]
my_list

[0, 1, 2, 3, 4]

In [12]:
my_list = [1,2,3,4,5]
my_list

[1, 2, 3, 4, 5]

In [20]:
# convert a list into an array
my_array = np.array(my_list)
print(my_array)

[1 2 3 4 5]


In [30]:
# an array of ONES
my_ones_array = np.ones([2,3])
print(my_ones_array)

[[1. 1. 1.]
 [1. 1. 1.]]


In [34]:
# an array of zeros
my_ones_array = np.zeros([3,2]) # 3 rows, 2 columns
print(my_ones_array)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [38]:
# an array of sevens
my_ones_array = np.full([3,2],7) # 3 rows, 2 columns
print(my_ones_array)

[[7 7]
 [7 7]
 [7 7]]


In [40]:
# an array of eight
my_ones_array = np.full([5,5],8) # 3 rows, 2 columns
print(my_ones_array)

[[8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]]


In [42]:
# identity matrix
id_n = np.eye(3)
print(id_n)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Basic Arithmetics

In [97]:
a = np.array([2,3,5,7,11,13])
b = np.array([2,4,6,8,10,12])

In [99]:
# additions
sum_a_b = a + b
print(sum_a_b)

[ 4  7 11 15 21 25]


In [101]:
# substraction
a_minus_b = a - b
print(a_minus_b)

[ 0 -1 -1 -1  1  1]


In [103]:
# multiplication
a_multiply_b = a * b
print(a_multiply_b)

[  4  12  30  56 110 156]


#### Aggregations

In [105]:
print(np.sum(a))
print(np.prod(a))
print(np.max(a))
print(np.min(a))

41
30030
13
2


#### Reshaping Arrays

In [107]:
a = np.array([1,2,3,5,7,10])

In [109]:
a_reshaped = a.reshape(3,2)
print(a_reshaped)

[[ 1  2]
 [ 3  5]
 [ 7 10]]


In [111]:
a.shape

(6,)

In [113]:
a_reshaped.shape

(3, 2)

#### Slicing an array

In [115]:
print(b)

[ 2  4  6  8 10 12]


In [117]:
print(b[3:])

[ 8 10 12]


#### Iterating/looping over arrays

In [119]:
print(b)

[ 2  4  6  8 10 12]


In [121]:
b.reshape(3,2)

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [125]:
for x in b:
    print(x)

2
4
6
8
10
12


In [131]:
# looping over a two dimensional array
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [141]:
for x in arr:
    for y in x:
      print(y)

1
2
3
4
5
6
7
8
9
10


In [ ]:
# looping over a two dimensional array
arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])

In [144]:
for x in arr:
    for y in x:
        for z in y:
            print (z)

TypeError: 'numpy.int32' object is not iterable